version: '3.8'

networks:
  hosting_network:
    external: true

services:
  portfolio_frontend:
    container_name: portfolio_frontend
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./client/build:/usr/share/nginx/html
    networks:
      - hosting_network
