name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Change working directory
        working-directory: ./portfolio/client
        run: |
          # Change the working directory to your app's folder
          cd client

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test  # Adjust this command to run your tests
        
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Change working directory
        working-directory: ./portfolio/client
        run: |
          # Change the working directory to your app's folder
          cd client


      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build  # Adjust this command to match your project's build script

  deploy:
    runs-on: ubuntu-latest

    needs: [build, test]  # Ensure build and test steps have completed successfully

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Change working directory
        working-directory: ./portfolio/client
        run: |
          # Change the working directory to your app's folder
          cd client
        
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "./portfolio/client/build"
          target: your_server_target_folder_path
          
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: docker-compose blah blah

